services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: fireinvent_keycloak
    restart: unless-stopped
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db_keycloak:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    depends_on:
      db_keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
  db_keycloak:
    image: postgres:18.1
    container_name: fireinvent_db_keycloak
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloakuser}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - db_keycloak_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER:-keycloakuser} -d ${KEYCLOAK_DB_NAME:-keycloak}"]
      interval: 5s
      timeout: 2s
      retries: 5
      
  keycloak_config:
    image: adorsys/keycloak-config-cli:latest-26
    container_name: fireinvent_keycloak_config
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      IMPORT_FILES_LOCATIONS: /config/*
      IMPORT_VARSUBSTITUTION_ENABLED: true
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      FIREINVENT_SPA_URL: ${FIREINVENT_SPA_URL}
      FIREINVENT_API_EXPLORER_URL: ${FIREINVENT_API_EXPLORER_URL}
      FIREINVENT_API_CLIENT_ID: ${FIREINVENT_API_CLIENT_ID}
      FIREINVENT_API_CLIENT_SECRET: ${FIREINVENT_API_CLIENT_SECRET}
    volumes:
      - ./config:/config:ro
volumes:
  db_keycloak_data: