realm: FireInvent
displayName: FireInvent
enabled: true

smtpServer:
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
  from: ${SMTP_FROM}
  fromDisplayName: "FireInvent"
  ssl: true
  starttls: true
  auth: true
  user: ${SMTP_USER}
  password: ${SMTP_PASSWORD}


clientScopes:
- name: roles
  protocol: openid-connect
  protocolMappers:
  - name: client roles
    protocolMapper: oidc-usermodel-client-role-mapper
    consentRequired: false
    config:
      "claim.name": "roles"
      "jsonType.label": "String"
      "multivalued": "true"
      "userinfo.token.claim": "true"
      "id.token.claim": "true"
      "access.token.claim": "true"

roles:
  realm:
  - name: admin
    description: Full application administration
  - name: procurement
    description: Inventory and order management
  - name: maintenance
    description: Maintenance management

clients:
- clientId: fireinvent-swagger
  name: FireInvent Swagger
  protocol: openid-connect
  publicClient: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  directAccessGrantsEnabled: false
  serviceAccountsEnabled: false
  attributes:
    "pkce.code.challenge.method": "S256"
  redirectUris:
  - $(env:FIREINVENT_SWAGGER_URL)/*
  webOrigins:
  - $(env:FIREINVENT_SWAGGER_URL)/*


# - clientId: fireinvent-spa
#   name: FireInvent SPA
#   protocol: openid-connect
#   publicClient: true
#   standardFlowEnabled: true
#   implicitFlowEnabled: false
#   directAccessGrantsEnabled: false
#   serviceAccountsEnabled: false
#   attributes:
#     "pkce.code.challenge.method": "S256"
#     "post.logout.redirect.uris": "${FIREINVENT_SPA_URL}/*"
#   redirectUris:
#   - ${FIREINVENT_SPA_URL}/*
#   webOrigins:
#   - ${FIREINVENT_SPA_URL}/*