using FireInvent.Contract;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FireInvent.Database.Models;

[Index(nameof(Name), IsUnique = true)]
public record Tenant
{
    /// <summary>
    /// Unique Identifier of the Tenant generated by Keycloak. (ID of the Keycloak organization)
    /// </summary>
    [Key]
    public Guid Id { get; set; }

    [Required]
    [MaxLength(ModelConstants.MaxStringLength)]
    public string Name { get; set; } = string.Empty;

    [MaxLength(ModelConstants.MaxStringLength)]
    public string? Description { get; set; }

    [Required]
    public DateTimeOffset CreatedAt { get; set; }
    
    public virtual ICollection<User> Users { get; set; } = [];
    
    public virtual ICollection<Item> Items { get; set; } = [];
    
    public virtual ICollection<Person> Persons { get; set; } = [];
    
    public virtual ICollection<Department> Departments { get; set; } = [];
    
    public virtual ICollection<StorageLocation> StorageLocations { get; set; } = [];
    
    public virtual ICollection<Order> Orders { get; set; } = [];
    
    public virtual ICollection<Appointment> Appointments { get; set; } = [];
    
    public virtual ICollection<ItemAssignmentHistory> AssignmentHistories { get; set; } = [];
    
    public virtual ICollection<Maintenance> Maintenances { get; set; } = [];
    
    public virtual ICollection<MaintenanceType> MaintenanceTypes { get; set; } = [];
    
    public virtual ICollection<Manufacturer> Manufacturers { get; set; } = [];
    
    public virtual ICollection<OrderItem> OrderItems { get; set; } = [];
    
    public virtual ICollection<ProductType> ProductTypes { get; set; } = [];
    
    public virtual ICollection<Product> Products { get; set; } = [];
    
    public virtual ICollection<Variant> Variants { get; set; } = [];
    
    public virtual ICollection<Visit> Visits { get; set; } = [];
    
    public virtual ICollection<VisitItem> VisitItems { get; set; } = [];
}
