// <auto-generated />
using System;
using FireInvent.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FireInvent.Database.Migrations;

[DbContext(typeof(GearDbContext))]
[Migration("20250603192831_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DepartmentPerson", b =>
            {
                b.Property<Guid>("DepartmentsId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PersonsId")
                    .HasColumnType("uuid");

                b.HasKey("DepartmentsId", "PersonsId");

                b.HasIndex("PersonsId");

                b.ToTable("DepartmentPerson");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Condition")
                    .HasColumnType("integer");

                b.Property<string>("Identifier")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<DateTime>("PurchaseDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("RetirementDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("StorageLocationId")
                    .HasColumnType("uuid");

                b.Property<Guid>("VariantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("Identifier")
                    .IsUnique();

                b.HasIndex("StorageLocationId");

                b.HasIndex("VariantId");

                b.ToTable("ClothingItems");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingItemAssignmentHistory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("AssignedFrom")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("AssignedUntil")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("ItemId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PersonId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("PersonId");

                b.HasIndex("ItemId", "AssignedFrom")
                    .IsUnique();

                b.ToTable("ClothingItemAssignmentHistories");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingProduct", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("Manufacturer")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Manufacturer");

                b.HasIndex("Name");

                b.HasIndex("Name", "Manufacturer")
                    .IsUnique();

                b.ToTable("ClothingProducts");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingVariant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("AdditionalSpecs")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("Name");

                b.HasIndex("ProductId", "Name")
                    .IsUnique();

                b.ToTable("ClothingVariants");
            });

        modelBuilder.Entity("FireInvent.Database.Models.Department", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Departments");
            });

        modelBuilder.Entity("FireInvent.Database.Models.Maintenance", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("ItemId")
                    .HasColumnType("uuid");

                b.Property<int>("MaintenanceType")
                    .HasColumnType("integer");

                b.Property<string>("PeformedById")
                    .HasColumnType("text");

                b.Property<DateTime>("PerformedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Remarks")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.HasKey("Id");

                b.HasIndex("ItemId");

                b.HasIndex("PeformedById");

                b.ToTable("Maintenances");
            });

        modelBuilder.Entity("FireInvent.Database.Models.Person", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ContactInfo")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("ExternalId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Remarks")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.HasKey("Id");

                b.HasIndex("ExternalId")
                    .IsUnique();

                b.HasIndex("FirstName");

                b.HasIndex("LastName");

                b.HasIndex("FirstName", "LastName")
                    .IsUnique();

                b.ToTable("Persons");
            });

        modelBuilder.Entity("FireInvent.Database.Models.StorageLocation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Remarks")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("StorageLocations");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("integer");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("boolean");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("boolean");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("text");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("boolean");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("text");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("boolean");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("AspNetUsers", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("text");

                b.Property<string>("ProviderKey")
                    .HasColumnType("text");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("text");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.Property<string>("RoleId")
                    .HasColumnType("text");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.Property<string>("LoginProvider")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<string>("Value")
                    .HasColumnType("text");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

        modelBuilder.Entity("DepartmentPerson", b =>
            {
                b.HasOne("FireInvent.Database.Models.Department", null)
                    .WithMany()
                    .HasForeignKey("DepartmentsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("FireInvent.Database.Models.Person", null)
                    .WithMany()
                    .HasForeignKey("PersonsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingItem", b =>
            {
                b.HasOne("FireInvent.Database.Models.StorageLocation", "StorageLocation")
                    .WithMany("StoredItems")
                    .HasForeignKey("StorageLocationId");

                b.HasOne("FireInvent.Database.Models.ClothingVariant", "Variant")
                    .WithMany("Items")
                    .HasForeignKey("VariantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("StorageLocation");

                b.Navigation("Variant");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingItemAssignmentHistory", b =>
            {
                b.HasOne("FireInvent.Database.Models.ClothingItem", "Item")
                    .WithMany("Assignments")
                    .HasForeignKey("ItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("FireInvent.Database.Models.Person", "Person")
                    .WithMany("AssignedItems")
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Item");

                b.Navigation("Person");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingVariant", b =>
            {
                b.HasOne("FireInvent.Database.Models.ClothingProduct", "Product")
                    .WithMany("Variants")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });

        modelBuilder.Entity("FireInvent.Database.Models.Maintenance", b =>
            {
                b.HasOne("FireInvent.Database.Models.ClothingItem", "Item")
                    .WithMany("Maintenances")
                    .HasForeignKey("ItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "PerformedBy")
                    .WithMany()
                    .HasForeignKey("PeformedById");

                b.Navigation("Item");

                b.Navigation("PerformedBy");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingItem", b =>
            {
                b.Navigation("Assignments");

                b.Navigation("Maintenances");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingProduct", b =>
            {
                b.Navigation("Variants");
            });

        modelBuilder.Entity("FireInvent.Database.Models.ClothingVariant", b =>
            {
                b.Navigation("Items");
            });

        modelBuilder.Entity("FireInvent.Database.Models.Person", b =>
            {
                b.Navigation("AssignedItems");
            });

        modelBuilder.Entity("FireInvent.Database.Models.StorageLocation", b =>
            {
                b.Navigation("StoredItems");
            });
#pragma warning restore 612, 618
    }
}
